name: movita_ecs
description: Sophisticated Flutter-based cross-platform device management application for system monitoring and device interaction

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_native_event_loop: ^1.0.8
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.3
  table_calendar: ^3.0.9
  path_provider: ^2.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/layouts/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/movita_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/movita_logo.png"
