name: movita_ecs
description: A cross-platform Flutter app for camera and device management with Movita ECS branding.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.3.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  web_socket_channel: ^2.4.0
  vector_math: ^2.1.4                        # For Matrix4 and Vector3 types
  table_calendar: ^3.0.9                     # For displaying a calendar widget
  # Media Kit for video playback
  media_kit: ^1.1.10                         # Primary package
  media_kit_video: 1.2.4                     # For video rendering (pinned version)
  media_kit_libs_android_video: ^1.3.6       # Android package
  media_kit_libs_ios_video: ^1.1.4           # iOS package
  media_kit_libs_macos_video: ^1.1.4         # macOS package
  media_kit_libs_windows_video: ^1.0.9       # Windows package
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/layouts/
  
  # Using system fonts instead of custom fonts for simplicity
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
