#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/smarteq/Flutter/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/smarteq/Desktop/Projects/Flutter/flutter-camera-device-management"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/smarteq/Desktop/Projects/Flutter/flutter-camera-device-management/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_DEV_DEPENDENCIES_ENABLED=true"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzIuMC0xLjAucHJlLjMyNg==,RkxVVFRFUl9DSEFOTkVMPW1hc3Rlcg==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049ZmZmZTM5NGNkZA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049ZmZmZTM5NGNkZA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My45LjAgKGJ1aWxkIDMuOS4wLTYzLjAuZGV2KQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/smarteq/Desktop/Projects/Flutter/flutter-camera-device-management/.dart_tool/package_config.json"
