#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/smarteq/Flutter/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/smarteq/Desktop/Projects/Flutter/flutter-camera-device-management"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_DEV_DEPENDENCIES_ENABLED=false"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzIuMC0xLjAucHJlLjQ2NQ==,RkxVVFRFUl9DSEFOTkVMPW1hc3Rlcg==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NzFjODQ3ZThiMA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NzFjODQ3ZThiMA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My45LjAgKGJ1aWxkIDMuOS4wLTk3LjAuZGV2KQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=/Users/smarteq/Desktop/Projects/Flutter/flutter-camera-device-management/.dart_tool/package_config.json"
